import type {
  WeeklyMeta,
  Deck,
  Event,
  Video,
  CardEvaluation,
  Guide,
  MatchupData,
} from "./types";

export const CURRENT_WEEK: WeeklyMeta = {
  weekStart: "2026-04-28",
  weekEnd: "2026-05-04",
  weekNumber: 18,
  format: "ローテーション",
  totalGames: 142831,
  summary:
    "今週はドラゴンが引き続き環境を支配。先週から+2.1%の上昇で使用率28.4%に達しました。ナイトメアが骸骨バフ型の台頭によりTier1に昇格。エルフはコンボ型が安定しTier2を維持しています。",
  classStats: [
    {
      className: "ドラゴン",
      usageRate: 28.4,
      winRate: 55.2,
      prevUsageRate: 26.3,
      prevWinRate: 54.1,
      tier: "S",
    },
    {
      className: "ナイトメア",
      usageRate: 25.0,
      winRate: 51.5,
      prevUsageRate: 24.5,
      prevWinRate: 51.2,
      tier: "S",
    },
    {
      className: "エルフ",
      usageRate: 17.8,
      winRate: 51.4,
      prevUsageRate: 18.6,
      prevWinRate: 51.8,
      tier: "A",
    },
    {
      className: "ウィッチ",
      usageRate: 13.5,
      winRate: 50.9,
      prevUsageRate: 12.9,
      prevWinRate: 50.2,
      tier: "A",
    },
    {
      className: "ロイヤル",
      usageRate: 10.1,
      winRate: 49.3,
      prevUsageRate: 11.3,
      prevWinRate: 49.8,
      tier: "A",
    },
    {
      className: "ビショップ",
      usageRate: 3.1,
      winRate: 45.8,
      prevUsageRate: 4.9,
      prevWinRate: 46.9,
      tier: "B",
    },
    {
      className: "ネメシス",
      usageRate: 2.1,
      winRate: 44.1,
      prevUsageRate: 3.5,
      prevWinRate: 45.2,
      tier: "C",
    },
  ],
};

export const DECK_RANKINGS: Deck[] = [
  {
    id: "deck-1",
    name: "加速ドラゴン",
    className: "ドラゴン",
    archetype: "Midrange",
    rank: 1,
    winRate: 54.1,
    usageRate: 22.4,
    prevWinRate: 53.0,
    difficulty: 2,
    costLevel: 3,
    tags: ["初心者向け", "大会実績あり", "安定"],
    description: "序盤からPPを加速させ、強力なドラゴンを早期召喚して圧倒するデッキ。",
    strategy:
      "序盤（1-3PP）は加速カードで手札を整え、中盤（4-6PP）に強力なフォロワーで盤面を制圧。終盤は疾走フォロワーでトドメを刺す。",
    keyCards: ["竜の加速師", "飛竜の斥候", "竜将バハムート", "古竜の覇者"],
    sampleCount: 18432,
  },
  {
    id: "deck-2",
    name: "骸骨バフナイトメア",
    className: "ナイトメア",
    archetype: "Midrange",
    rank: 2,
    winRate: 52.8,
    usageRate: 14.8,
    prevWinRate: 50.6,
    difficulty: 3,
    costLevel: 2,
    tags: ["低コスト", "上昇トレンド", "大会実績あり"],
    description: "骸骨を大量展開しバフをかけることで圧倒的な盤面を形成するデッキ。",
    strategy:
      "骸骨系フォロワーを展開しつつ、バフカードで一気に強化。相手の除去が間に合わないうちに盤面勝ちを狙う。",
    keyCards: ["骸骨の王", "死の舞踏", "ゴーストライダー", "骨の軍勢"],
    sampleCount: 12104,
  },
  {
    id: "deck-3",
    name: "コンボエルフ",
    className: "エルフ",
    archetype: "Combo",
    rank: 3,
    winRate: 51.9,
    usageRate: 12.3,
    prevWinRate: 52.1,
    difficulty: 4,
    costLevel: 3,
    tags: ["上級者向け", "高火力", "スキル重要"],
    description: "手札を大量消費するコンボで一ターンに大ダメージを叩き込むエルフデッキ。",
    strategy:
      "序盤は手札を温存しつつ展開を防ぎ、コンボパーツが揃った瞬間に一気に決める。マリガンが非常に重要。",
    keyCards: ["妖精の長弓手", "森の意志", "エルフの少女リザ", "妖精の輪舞"],
    sampleCount: 10087,
  },
  {
    id: "deck-4",
    name: "秘術ウィッチ",
    className: "ウィッチ",
    archetype: "Control",
    rank: 4,
    winRate: 50.9,
    usageRate: 9.8,
    prevWinRate: 50.2,
    difficulty: 3,
    costLevel: 3,
    tags: ["コントロール", "土の秘術"],
    description: "土の秘術を軸に相手の動きを全て打ち消しながら戦うコントロールデッキ。",
    strategy:
      "秘術カウントを稼ぎながら相手のフォロワーを除去し続ける。十分なカウントが貯まったらフィニッシャーで一気に決着。",
    keyCards: ["ルーンの魔法使い", "土の秘術師", "マジックミサイル", "大魔法使いマーリン"],
    sampleCount: 8034,
  },
  {
    id: "deck-5",
    name: "兵団ロイヤル",
    className: "ロイヤル",
    archetype: "Aggro",
    rank: 5,
    winRate: 49.8,
    usageRate: 7.2,
    prevWinRate: 50.1,
    difficulty: 2,
    costLevel: 2,
    tags: ["アグロ", "低コスト", "序盤強い"],
    description: "低コストの兵士フォロワーを連打して早期決着を狙うアグレッシブなデッキ。",
    strategy: "1〜3PPの強力なフォロワーを連打して序盤から圧力をかける。6ターン以内の決着を目指す。",
    keyCards: ["精鋭の剣士", "騎士団の指揮官", "英雄の剣", "旗手の号令"],
    sampleCount: 5891,
  },
  {
    id: "deck-6",
    name: "狂乱ナイトメア",
    className: "ナイトメア",
    archetype: "Aggro",
    rank: 6,
    winRate: 47.8,
    usageRate: 4.1,
    prevWinRate: 48.9,
    difficulty: 3,
    costLevel: 2,
    tags: ["自傷", "ハイリスク", "上昇期待"],
    description: "自分にダメージを与えることで強化される狂乱状態を活かすアグロデッキ。",
    strategy: "自傷カードで狂乱状態を早期に達成し、強化されたフォロワーで一気に畳み込む。",
    keyCards: ["血の渇望", "狂乱の吸血鬼", "夜の捕食者", "血染めの薔薇"],
    sampleCount: 3362,
  },
];

export const EVENTS: Event[] = [
  {
    id: "event-1",
    title: "ランクマッチ Season 12",
    type: "season",
    status: "ongoing",
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    description:
      "Season 12のランクマッチ。マスター到達でシーズン限定スリーブがもらえます。上位プレイヤーには追加報酬あり。",
    format: "ローテーション",
    prizePool: "シーズン報酬カード、プレミアムチケット",
  },
  {
    id: "event-2",
    title: "グランプリ Vol.12",
    type: "grand_prix",
    status: "ongoing",
    startDate: "2026-04-29",
    endDate: "2026-05-07",
    description:
      "今期のグランプリ。ローテーション形式のBO1。上位入賞でグランプリポイントと限定スリーブを獲得できます。",
    format: "ローテーション",
    prizePool: "グランプリポイント、限定スリーブ「龍神の加護」",
    officialUrl: "https://shadowverse.jp",
  },
  {
    id: "event-3",
    title: "SV World Beyond 公式選手権 2026 Spring",
    type: "official",
    status: "upcoming",
    startDate: "2026-05-10",
    endDate: "2026-05-11",
    description:
      "春季公式選手権。スイスドロー→シングルエリミネーション形式。事前申込制。優勝賞金30万円＋招待権。",
    format: "ローテーション",
    prizePool: "優勝賞金 ¥300,000 + 招待権",
    officialUrl: "https://shadowverse.jp",
  },
  {
    id: "event-4",
    title: "コミュニティカップ #28",
    type: "cup",
    status: "upcoming",
    startDate: "2026-05-17",
    endDate: "2026-05-17",
    description: "コミュニティ主催のBO3大会。アンリミテッド形式。参加無料。",
    format: "アンリミテッド",
    prizePool: "Amazonギフト券 ¥10,000",
  },
  {
    id: "event-5",
    title: "グランプリ Vol.11",
    type: "grand_prix",
    status: "ended",
    startDate: "2026-04-15",
    endDate: "2026-04-22",
    description: "前期グランプリ。ドラゴンが上位を席巻した大会となりました。",
    format: "ローテーション",
    prizePool: "グランプリポイント、限定スリーブ「蒼海の竜騎士」",
  },
];

export const VIDEOS: Video[] = [
  {
    id: "video-1",
    youtubeId: "dQw4w9WgXcQ",
    title: "【完全解説】加速ドラゴンで勝率80%達成する方法【シャドウバースWB】",
    channelName: "SV攻略チャンネル",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-05-02",
    viewCount: 242000,
    durationSec: 1023,
    classTags: ["ドラゴン"],
    tags: ["デッキ解説", "初心者向け", "加速ドラゴン"],
    isCurated: true,
    curationNote: "加速ドラゴンを始める人はまずこの動画から。マリガン基準まで丁寧に解説されています。",
  },
  {
    id: "video-2",
    youtubeId: "dQw4w9WgXcQ",
    title: "【週刊メタ動画 #52】Week18 環境総まとめ　ネクロが強い理由を徹底解説",
    channelName: "メタ分析TV",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-05-01",
    viewCount: 187000,
    durationSec: 1421,
    classTags: ["ナイトメア", "ドラゴン"],
    tags: ["メタ解説", "環境考察", "週次"],
    isCurated: true,
    curationNote: "今週の環境を俯瞰で理解したいならこの動画。ネクロ昇格の理由が明快に解説されています。",
  },
  {
    id: "video-3",
    youtubeId: "dQw4w9WgXcQ",
    title: "骸骨バフネクロマスター降臨！グランプリ予選全勝の立ち回りを全公開",
    channelName: "プロプレイヤーXX",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-04-30",
    viewCount: 121000,
    durationSec: 1887,
    classTags: ["ナイトメア"],
    tags: ["対戦動画", "グランプリ", "上級者向け"],
    isCurated: false,
  },
  {
    id: "video-4",
    youtubeId: "dQw4w9WgXcQ",
    title: "【初心者必見】コンボエルフの理想ムーブを徹底解説！マリガンから勝ち筋まで",
    channelName: "テクニカルSV",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-04-28",
    viewCount: 93000,
    durationSec: 1543,
    classTags: ["エルフ"],
    tags: ["デッキ解説", "コンボエルフ", "初心者向け"],
    isCurated: true,
    curationNote: "コンボエルフのコンボルートをわかりやすく図解付きで解説。上級者でも気づきがある内容。",
  },
  {
    id: "video-5",
    youtubeId: "dQw4w9WgXcQ",
    title: "秘術ウィッチで上位マスター到達！コントロールの真髄を見せます",
    channelName: "ウィッチマスター",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-04-27",
    viewCount: 67000,
    durationSec: 2234,
    classTags: ["ウィッチ"],
    tags: ["対戦動画", "コントロール", "上位マスター"],
    isCurated: false,
  },
  {
    id: "video-6",
    youtubeId: "dQw4w9WgXcQ",
    title: "【2026年5月最新版】シャドウバースWB 初心者が最初にやるべきこと10選",
    channelName: "SV攻略チャンネル",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    publishedAt: "2026-04-25",
    viewCount: 312000,
    durationSec: 912,
    classTags: [],
    tags: ["初心者向け", "始め方", "お役立ち"],
    isCurated: true,
    curationNote: "WBを始めたばかりの人向け。リソース管理からカード資産の考え方まで網羅。",
  },
];

export const CARD_EVALUATIONS: CardEvaluation[] = [
  {
    id: "card-1",
    cardName: "古竜の覇者",
    className: "ドラゴン",
    rarity: "Legendary",
    cost: 8,
    setName: "覚醒の神々",
    rating: "S",
    publishedAt: "2026-04-20",
    summary: "加速ドラゴンのフィニッシャーとして環境トップに君臨。4枚必須級のレジェンド。",
    description:
      "8PPと重いが、PPブーストが得意なドラゴンであれば5〜6ターン目に出すことも可能。突進と疾走を持ち、出た瞬間にゲームを終わらせるポテンシャルがある。今環境のドラゴンデッキには4枚必須。コスト対策としての生成優先度は最高クラス。",
  },
  {
    id: "card-2",
    cardName: "骸骨の王",
    className: "ナイトメア",
    rarity: "Gold",
    cost: 5,
    setName: "覚醒の神々",
    rating: "S",
    publishedAt: "2026-04-22",
    summary: "骸骨バフネクロの核。単体でも強力で、バフがかかると手がつけられない。",
    description:
      "召喚時に骸骨トークンを2体生成し、バフカードとの組み合わせで爆発的な盤面を形成。5PPという軽さも魅力で、序盤から中盤の動きをスムーズに繋いでくれる。ネクロを使うなら4枚確保必須。",
  },
  {
    id: "card-3",
    cardName: "大魔法使いマーリン",
    className: "ウィッチ",
    rarity: "Legendary",
    cost: 7,
    setName: "覚醒の神々",
    rating: "A",
    publishedAt: "2026-04-23",
    summary: "秘術ウィッチの頂点フィニッシャー。秘術カウント20で真の力を発揮する。",
    description:
      "秘術カウント20を達成すると全体3点+疾走4/4形態に変身。コントロール環境では非常に強力だが、現環境のアグロに対しては少々重い場面も。2〜3枚採用が一般的。",
  },
  {
    id: "card-4",
    cardName: "妖精の長弓手",
    className: "エルフ",
    rarity: "Silver",
    cost: 2,
    setName: "覚醒の神々",
    rating: "A",
    publishedAt: "2026-04-24",
    summary: "コンボエルフの回転を加速させる縁の下の力持ち。地味だが必須カード。",
    description:
      "手札が5枚以上の場合にコストが1になる効果を持ち、エルフのコンボ性能を大幅に引き上げる。単体では地味だが、デッキの核を担う1枚。4枚確定。",
  },
  {
    id: "card-5",
    cardName: "聖弓の守護天使",
    className: "ビショップ",
    rarity: "Gold",
    cost: 4,
    setName: "覚醒の神々",
    rating: "B",
    publishedAt: "2026-04-25",
    summary: "ビショップの回復を底上げするが、現環境では活躍の場が限られる。",
    description:
      "召喚時に体力を4回復し、守護を持つ4/4フォロワー。回復型ビショップには必須だが、現環境ではビショップ自体がTier3のため採用機会は限定的。ビショップ愛好家は確保推奨。",
  },
];

export const GUIDES: Guide[] = [
  {
    id: "guide-1",
    title: "シャドウバースWB 完全初心者ガイド 2026年版",
    category: "beginner",
    publishedAt: "2026-04-01",
    updatedAt: "2026-05-01",
    summary:
      "WBを始めたばかりの方向け。ゲームの基本ルールから最初にやるべきことまで完全解説。",
    readMinutes: 12,
    tags: ["初心者", "基本ルール", "始め方"],
  },
  {
    id: "guide-2",
    title: "【クラス別】ドラゴン入門ガイド — 基本戦術とおすすめデッキ",
    category: "class",
    className: "ドラゴン",
    publishedAt: "2026-04-05",
    updatedAt: "2026-05-02",
    summary:
      "ドラゴンクラスの特徴であるPP加速を活かした立ち回りを徹底解説。環境最強クラスを使いこなそう。",
    readMinutes: 8,
    tags: ["ドラゴン", "クラスガイド", "加速"],
  },
  {
    id: "guide-3",
    title: "予算3,000円で作れる！コスパ最強デッキ3選",
    category: "budget",
    publishedAt: "2026-04-10",
    updatedAt: "2026-04-28",
    summary: "課金を最小限に抑えながらランクマッチで勝てるデッキを厳選。学生・無課金勢にもおすすめ。",
    readMinutes: 10,
    tags: ["低コスト", "無課金", "節約"],
  },
  {
    id: "guide-4",
    title: "マリガンの考え方 — 初心者が最も差をつけられるポイント",
    category: "beginner",
    publishedAt: "2026-04-15",
    updatedAt: "2026-04-15",
    summary:
      "ゲームの勝率を大きく左右するマリガン（初手の入れ替え）の基本的な考え方を解説。",
    readMinutes: 6,
    tags: ["マリガン", "基礎", "思考法"],
  },
  {
    id: "guide-5",
    title: "グランプリ初挑戦ガイド — 準備から本番まで完全解説",
    category: "advanced",
    publishedAt: "2026-04-20",
    updatedAt: "2026-04-29",
    summary: "グランプリに初めて参加する方向け。デッキ選択から当日の立ち回りまで全てわかります。",
    readMinutes: 15,
    tags: ["グランプリ", "大会", "競技"],
  },
  {
    id: "guide-6",
    title: "【クラス別】ナイトメア入門ガイド — 骸骨バフの使い方",
    category: "class",
    className: "ナイトメア",
    publishedAt: "2026-04-22",
    updatedAt: "2026-05-01",
    summary: "現在Tier1に昇格したナイトメアの使い方を基礎から解説。今すぐ乗り換えを検討しよう。",
    readMinutes: 9,
    tags: ["ナイトメア", "クラスガイド", "骸骨バフ"],
  },
];

export const MATCHUP_DATA: MatchupData[] = [
  { classA: "ドラゴン", classB: "ナイトメア", winRateA: 54, sampleCount: 8234 },
  { classA: "ドラゴン", classB: "エルフ", winRateA: 58, sampleCount: 7891 },
  { classA: "ドラゴン", classB: "ウィッチ", winRateA: 52, sampleCount: 5432 },
  { classA: "ドラゴン", classB: "ロイヤル", winRateA: 61, sampleCount: 4821 },
  { classA: "ドラゴン", classB: "ナイトメア", winRateA: 59, sampleCount: 2341 },
  { classA: "ドラゴン", classB: "ビショップ", winRateA: 65, sampleCount: 1234 },
  { classA: "ドラゴン", classB: "ネメシス", winRateA: 70, sampleCount: 876 },
  { classA: "ナイトメア", classB: "エルフ", winRateA: 51, sampleCount: 6234 },
  { classA: "ナイトメア", classB: "ウィッチ", winRateA: 55, sampleCount: 4123 },
  { classA: "ナイトメア", classB: "ロイヤル", winRateA: 57, sampleCount: 3421 },
  { classA: "エルフ", classB: "ウィッチ", winRateA: 53, sampleCount: 5432 },
  { classA: "エルフ", classB: "ロイヤル", winRateA: 56, sampleCount: 4321 },
  { classA: "ウィッチ", classB: "ロイヤル", winRateA: 55, sampleCount: 3211 },
];

export const PREV_WEEKS_WINRATE = [
  { week: "4/20", ドラゴン: 52.1, ナイトメア: 50.3, ウィッチ: 49.8, ロイヤル: 48.5, エルフ: 48.2 },
  { week: "4/27", ドラゴン: 53.2, ナイトメア: 51.2, ウィッチ: 50.2, ロイヤル: 49.1, エルフ: 49.5 },
  { week: "5/4",  ドラゴン: 54.0, ナイトメア: 52.0, ウィッチ: 50.5, ロイヤル: 49.5, エルフ: 50.8 },
  { week: "5/11", ドラゴン: 54.8, ナイトメア: 52.4, ウィッチ: 50.8, ロイヤル: 49.8, エルフ: 51.0 },
  { week: "5/18", ドラゴン: 55.2, ナイトメア: 52.8, ウィッチ: 50.9, ロイヤル: 49.3, エルフ: 51.4 },
];

export const PREV_WEEKS_USAGE = [
  {
    week: "Week 15",
    ドラゴン: 22.1,
    ナイトメア: 15.2,
    エルフ: 20.3,
    ウィッチ: 12.8,
    ロイヤル: 13.5,
  },
  {
    week: "Week 16",
    ドラゴン: 24.3,
    ナイトメア: 16.1,
    エルフ: 19.8,
    ウィッチ: 12.5,
    ロイヤル: 12.8,
  },
  {
    week: "Week 17",
    ドラゴン: 26.3,
    ナイトメア: 17.8,
    エルフ: 18.6,
    ウィッチ: 12.9,
    ロイヤル: 11.3,
  },
  {
    week: "Week 18",
    ドラゴン: 28.4,
    ナイトメア: 19.2,
    エルフ: 17.8,
    ウィッチ: 13.5,
    ロイヤル: 10.1,
  },
];
